model_list: []

general_settings:
  master_key: ${LITELLM_MASTER_KEY}
  store_model_in_db: true

litellm_settings:
  modify_params: true

guardrails:
  - guardrail_name: presidio-pre-guard
    litellm_params:
      guardrail: presidio
      mode: pre_call
